- hosts: app
  become: true
  collections:
    - community.docker

  tasks:
    - name: Install required packages
      apt:
        name:
          - docker.io
          - python3-pip
        update_cache: yes
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Stop existing container (if any)
      community.docker.docker_container:
        name: myapp
        state: stopped
      ignore_errors: yes

    - name: Remove existing container (if any)
      community.docker.docker_container:
        name: myapp
        state: absent
      ignore_errors: yes

    - name: Pull Docker image
      community.docker.docker_image:
        name: "vaibhavgumalwad/myapp"
        tag: "{{ git_commit }}"
        source: pull

    - name: Run container
      community.docker.docker_container:
        name: myapp
        image: "vaibhavgumalwad/myapp:{{ git_commit }}"
        state: started
        restart_policy: unless-stopped
        ports:
          - "80:80"
